name: Laravel 

on:
  push:
    branches: 
      - main
      - dev
      - acc/test
      - prod
  pull_request:
    branches: 
      - main
      - dev
      - acc/test
      - prod

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Ensure .env File Exists
        run: |
          if [ ! -f .env ]; then
            if [ -f .env.example ]; then
              cp .env.example .env
            else
              echo "Missing .env.example file!"
              exit 1
            fi
          fi

      - name: Update .env for MySQL
        run: |
          sed -i 's/DB_CONNECTION=.*/DB_CONNECTION=mysql/' .env
          sed -i 's/DB_HOST=.*/DB_HOST=127.0.0.1/' .env
          sed -i 's/DB_PORT=.*/DB_PORT=3306/' .env
          sed -i 's/DB_DATABASE=.*/DB_DATABASE=laravel_test/' .env
          sed -i 's/DB_USERNAME=.*/DB_USERNAME=root/' .env
          sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=/' .env

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      

      - name: Update .env for New MySQL User
        run: |
          sed -i 's/DB_CONNECTION=.*/DB_CONNECTION=mysql/' .env
          sed -i 's/DB_HOST=.*/DB_HOST=127.0.0.1/' .env
          sed -i 's/DB_PORT=.*/DB_PORT=3306/' .env
          sed -i 's/DB_DATABASE=.*/DB_DATABASE=laravel_test/' .env
          sed -i 's/DB_USERNAME=.*/DB_USERNAME=laravel_user/' .env
          sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=password123/' .env


      - name: Set Up MySQL Service
        run: |
          sudo service mysql start# Create a new user and grant privileges
          sudo mysql -e "CREATE USER 'laravel_user'@'localhost' IDENTIFIED BY 'password123';"
          sudo mysql -e "CREATE DATABASE laravel_test;"
          sudo mysql -e "GRANT ALL PRIVILEGES ON laravel_test.* TO 'laravel_user'@'localhost';"
          sudo mysql -e "FLUSH PRIVILEGES;"
      - name: Run Migrations
        env:
          DB_CONNECTION: mysql
          DB_HOST: mysql
          DB_PORT: 3306
          DB_DATABASE: twitter
          DB_USERNAME: sail
          DB_PASSWORD: password
        run: php artisan migrate

      - name: Execute Tests (Unit and Feature Tests) via PHPUnit/Pest
        env:
          DB_CONNECTION: mysql
          DB_HOST: mysql
          DB_PORT: 3306
          DB_DATABASE: twitter
          DB_USERNAME: sail
          DB_PASSWORD: password
        run: sudo /etc/init.d/mysql start
             php artisan test
  
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install NPM Dependencies
        run: npm install
      - name: Build Assets
        run: npm run build
