name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    # Set up PHP
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2' # PHP version required by your composer.json

    # Check out the repository
    - uses: actions/checkout@v4

    # Copy the .env file
    - name: Copy .env
      run: |
        if [ ! -f ".env" ]; then
          if [ -f ".env.example" ]; then
            cp .env.example .env
          else
            echo "APP_NAME=Laravel" > .env
            echo "APP_ENV=local" >> .env
            echo "APP_KEY=" >> .env
            echo "APP_DEBUG=true" >> .env
            echo "APP_URL=http://localhost" >> .env
          fi
        fi

    # Install Composer dependencies
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    # Generate application key
    - name: Generate key
      run: php artisan key:generate

    # Set directory permissions
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    # Create SQLite database
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite

    # Run tests using PHPUnit or Pest
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test
