name: CI/CD Pipeline (Laravel)

# **Continuous Integration**: On every push to the main branch, GitHub Actions will automatically: Install dependencies, Run tests using PHPUnit.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Ensure .env File Exists
        run: |
          if [ ! -f .env ]; then
            if [ -f .env.example ]; then
              cp .env.example .env
            else
              echo "Missing .env.example file!"
              exit 1
            fi
          fi

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate application key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Execute Tests (Unit and Feature Tests) via PHPUnit/Pest
        env:
          DB_CONNECTION: mysql
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: sudo /etc/init.d/mysql start
             php artisan test

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Ensure Node.js 17 or higher

  tdd-checks:
    runs-on: ubuntu-latest
    needs: laravel-tests
    steps:
      # Verify that failing tests are resolved
      - name: Check for Resolved Tests
        run: |
          echo "Ensuring TDD principles are met..."
          

      - name: Install NPM Dependencies
        run: npm install

      - name: Build Assets
        run: npm run build
