name: Twittertest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install Composer Dependencies
      run: composer install --optimize-autoloader --no-interaction --no-progress --no-dev --prefer-dist

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Updated to Node.js version 18

    - name: Install NPM Dependencies
      run: npm install

    - name: Build Project
      run: npm run build

    - name: Synchronize Files To Server
      uses: easingthemes/ssh-deploy@v2.1.1
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-avz --delete"
        SOURCE: "public/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_PATH }}

    - name: Run Remote/Artisan Commands
      uses: easingthemes/ssh-deploy@v2.1.1
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: ""
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_PATH }}
        COMMANDS: |
          cd ${{ secrets.REMOTE_PATH }}
          php artisan migrate --force
          php artisan optimize
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          php artisan queue:restart
